services:
  batch:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "7"
